name: "DEV DEPLOY"

on:
    push:
        branches:
            - develop

permissions:
    id-token: write
    contents: read

jobs:
    terraform:
        uses: ./.github/workflows/terraform.yml
        with:
            environment: "dev"
            aws-assume-role-arm: "arn:aws:iam::982081072219:role/github-actions-LeandroTinoco-pipeline"
            aws-region: "sa-east-1"
            aws-statefile-s3-bucket: "leandrotinoco-sa-east-1-terraform-statefile"
            aws-lock-dynamodb-table: "leandrotinoco-sa-east-1-terraform-lock"
